<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Calculator.Bootstrapper\Calculator.Bootstrapper.csproj" />
		<ProjectReference Include="..\Calculator.Common\Calculator.Common.csproj" />
		<ProjectReference Include="..\Calculator.Parser\Calculator.Parser.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Config\operators.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
